item {
  id: 1
  name: 'Car'
}

item {
  id: 2
  name: 'Truck'
}

item {
  id: 3
  name: 'Tractor-Trailer'
}

item {
  id: 4
  name: 'Bus'
}

item {
  id: 5
  name: 'Container'
}

item {
  id: 6
  name: 'Boat'
}

item {
  id: 7
  name: 'Plane'
}

item {
  id: 8
  name: 'Helicopter'
}

item {
  id: 9
  name: 'Person'
}

item {
  id: 10
  name: 'Cyclist'
}

item {
  id: 11
  name: 'DCR'
}
